# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fec5e9b335418cb8e1405ff2326d4c2ae65388f95b18a60c8817fda0c6ef82f23e4e4ad9148905df16b1ae89e11bdfe2b703a52002376735a98e1628a2ee40b7

test:
  secret_key_base: dc9a99248400c6929fde97bdf5aaed2ce7059b50c46dc02b249ea9db29fb47bcf31ec5d3bc1f645882e9da171d081793b3fed454d263aa87a2facdd3fda5e085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
